# Generated by Django 4.2.4 on 2023-08-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
